spring.application.name=PieJuega
# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/piejuega_db
spring.datasource.username=piejuega
spring.datasource.password=piejuega123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JWT
# ===============================
jwt.secret=very_secret_key_change_in_prod_123456
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000
# ===============================
# SERVER
# ===============================
server.port=8080
# ===============================
# OAUTH2 - GOOGLE
# ===============================

spring.security.oauth2.client.registration.google.client-id=1050830825204-2k5d2sn2ptpobfdv4l5u67q3bc3lh6fi.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
