spring.application.name=PieJuega

# Activar perfil
spring.profiles.active=dev

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# FIREBASE CLOUD MESSAGING
# ===============================
firebase.project-id=${FIREBASE_PROJECT_ID:piejuega-5c819}
firebase.messaging.enabled=${FIREBASE_MESSAGING_ENABLED:true}














