package com.example.PieJuega.util;

public enum NotificationType {
    RESERVATION_REQUEST,
    RESERVATION_APPROVED,
    RESERVATION_REJECTED,
    RESERVATION_CANCELLED,
    TOURNAMENT_REQUEST,
    TOURNAMENT_APPROVED,
    TOURNAMENT_REJECTED,
    TOURNAMENT_CANCELLED,
    TOURNAMENT_REGISTRATION,
    TEAM_ADDED,
    CHAT_MESSAGE
}
